name: delft3dfmpy
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8.*
  - git=2.30.0
  - pip=21.0
  - ipykernel=5.4.3
  - ipywidgets=7.6.3
  - geopandas=0.8.2
  - rasterio=1.2.0
  - imod=0.10.1
  - numpy=1.19.5
  - scipy=1.6.0
  - pandas=1.2.1
  - matplotlib=3.3.3
  - pillow=8.1.0
  - rasterstats=0.14.0
  - tqdm=4.56.0
  - netcdf4=1.5.5.1
  - descartes=1.1.0
  - contextily=1.0.1
  - fire=0.4.0
  - rstr=2.2.6  
  - pip:
    - hkvsobekpy==1.5